config/routes.rb
Communities::Application.routes.draw do

  resources :communities, path: "game" do
    resources :community_topics, path: "topic", as: "topic"
  end

  root :to => 'communities#index'
end

app/models/community.rb
class Community < ActiveRecord::Base
  attr_accessible :description, :name, :slug

  validate :name, presence: true, uniqueness: true

  has_many :community_topics, dependent: :destroy

  def to_param
    slug
  end
end

app/models/community_topic.rb
class CommunityTopic < ActiveRecord::Base
  attr_accessible :community_id, :name

  belongs_to :community
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_filter :find_community, except: :index

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @communities }
    end
  end

  # GET /communities/1
  # GET /communities/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/new
  # GET /communities/new.json
  def new
    @community = Community.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @community }
    end
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(params[:community])
    @community.slug = @community.name.parameterize

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render json: @community, status: :created, location: @community }
      else
        format.html { render action: "new" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /communities/1
  # PUT /communities/1.json
  def update

    respond_to do |format|
      if @community.update_attributes(params[:community])
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url }
      format.json { head :no_content }
    end
  end

  private
  def find_community
    # @community = Community.find params[:id] # without to_param
    @community = Community.find_by_slug params[:id] # with to_param
  end
end

app/controllers/community_topics_controller.rb
class CommunityTopicsController < ApplicationController

  before_filter :find_community

  # GET /community_topics
  # GET /community_topics.json
  def index
    @community_topics = CommunityTopic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @community_topics }
    end
  end

  # GET /community_topics/1
  # GET /community_topics/1.json
  def show
    @community_topic = CommunityTopic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @community_topic }
    end
  end

  # GET /community_topics/new
  # GET /community_topics/new.json
  def new
    @community_topic = CommunityTopic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @community_topic }
    end
  end

  # GET /community_topics/1/edit
  def edit
    @community_topic = CommunityTopic.find(params[:id])
  end

  # POST /community_topics
  # POST /community_topics.json
  def create
    @community_topic = CommunityTopic.new(params[:community_topic])

    respond_to do |format|
      if @community_topic.save
        format.html { redirect_to [@community, @community_topic], notice: 'Community topic was successfully created.' }
        format.json { render json: [@community, @community_topic], status: :created, location: @community_topic }
      else
        format.html { render action: "new" }
        format.json { render json: @community_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /community_topics/1
  # PUT /community_topics/1.json
  def update
    @community_topic = CommunityTopic.find(params[:id])

    respond_to do |format|
      if @community_topic.update_attributes(params[:community_topic])
        format.html { redirect_to [@community, @community_topic], notice: 'Community topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @community_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_topics/1
  # DELETE /community_topics/1.json
  def destroy
    @community_topic = CommunityTopic.find(params[:id])
    @community_topic.destroy

    respond_to do |format|
      format.html { redirect_to community_topics_url }
      format.json { head :no_content }
    end
  end

  private
  def find_community
    # @community = Community.find params[:community_id] # without to_param
    @community = Community.find_by_slug params[:community_id] # with to_param
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_topics_helper.rb
module CommunityTopicsHelper
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing community</h1>

<%= render 'form' %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Listing communities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @communities.each do |community| %>
  <tr>
    <td><%= community.name %></td>
    <td><%= community.description %></td>
    <td><%= link_to 'Show', community %></td>
    <td><%= link_to 'Edit', edit_community_path(community) %></td>
    <td><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New community</h1>

<%= render 'form' %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @community.name %>
</p>

<p>
  <b>Description:</b>
  <%= @community.description %>
</p>

<h3>Topics</h3>
<ul>
  <% @community.community_topics.each do |topic| %>
    <li><%= link_to topic.name, [@community, topic] %></li>
  <% end %>
</ul>


<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>

app/views/community_topics/_form.html.erb
<%= form_for([@community, @community_topic]) do |f| %>
  <% if @community_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community_topic.errors.count, "error") %> prohibited this community_topic from being saved:</h2>

      <ul>
      <% @community_topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :community_id %><br />
    <%= f.number_field :community_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/community_topics/edit.html.erb
<h1>Editing community_topic</h1>

<%= render 'form' %>

<%= link_to 'Show', [@community, @community_topic] %> |
<%= link_to 'Back', community_community_topics_path(@community) %>

app/views/community_topics/index.html.erb
<h1>Listing community_topics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Community</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @community_topics.each do |community_topic| %>
  <tr>
    <td><%= community_topic.name %></td>
    <td><%= community_topic.community_id %></td>
    <td><%= link_to 'Show', [@community, community_topic] %></td>
    <td><%= link_to 'Edit', [:edit, @community, community_topic] %></td>
    <td><%= link_to 'Destroy', [@community, community_topic], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Community topic', new_community_topic_path(@community) %>

app/views/community_topics/new.html.erb
<h1>New community_topic</h1>

<%= render 'form' %>

<%= link_to 'Back', community_topic_index_path(@community) %>

app/views/community_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @community_topic.name %>
</p>

<p>
  <b>Community:</b>
  <%= @community_topic.community_id %>
</p>


<%= link_to 'Edit', edit_community_topic_path(@community, @community_topic) %> |
<%= link_to 'Back', community_topic_index_path(@community) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Communities</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>